m3ntorship/charity

firebase.json
https://nilegfx.charity.m3ntorship.com/
=> add firebase rewrites for all sites

.gitignore, package-lock.json, package.json, postcss.config.js, tailwind.config.js, tailwind.css
https://app.clickup.com/t/4pq9nr
=> Introducing tailwind

dist/index.html
I added The markup of the site ( HTML Placeholders )
https://m3-charity-malngaawy.web.app/
=> html-placeholers

dist/assets/css/main.css, dist/index.html
- Added separate a CSS file for every section
- Added a CSS file for global styles
- Imported all the created CSS files in main.css
- Linked main.css in index.html
=> Added a CSS file for every section

dist/typography.html
https://mohassn.charity.m3ntorship.com/
=> add typography preview file

.github/workflows/deploy-firebase-live.yml, .github/workflows/deploy-firebase-user.yml
- install tailwind dependencies before running the build
- build css file
http://nilegfx.charity.m3ntorship.com/
=> install dependencies & build dist before deploying

dist/typography.html, src/css/global.css
i added The Three Several Buttons styles 
large button (btn-lg)
medium button (btn-md)
small button (btn-sm)
and edit the css link href in Typography to ( main.css )
You Can See The Different Between Them in Typography.html
=> Add several btn

dist/index.html
https://abudzohair.charity.m3ntorship.com/
=> Style donation banner button

src/css/global.css, src/css/main.css
https://app.clickup.com/t/4rm0z8
=> Container global class changes & tailwind utilities overriding global

dist/index.html, src/css/work-style.css
I Just fix the small div in this section to deal with the designe
=> Fix work style

dist/index.html, src/css/donation-banner.css
ticket: https://app.clickup.com/t/4uj5v1
live: https://abdomgdy.charity.m3ntorship.com/
=> changed font-size and border width to match psd

src/css/work-style.css
[My site](https://mohassn.charity.m3ntorship.com/)
[Ticket on clickup](https://app.clickup.com/t/4ukg2t)
=> fix: spacing in how we work section

dist/index.html, src/css/causes.css
[My site](https://mohassn.charity.m3ntorship.com/)
[Ticket on clickup](https://app.clickup.com/t/4uj6he)
=> fix popular causes section issues

dist/index.html, src/css/feedback.css, src/css/work-style.css
Ticket : https://app.clickup.com/t/4uj8ej
=> Fix: people-feedback & work-style

src/components/Activities/styles.css
added style for Activities Component
=> added style for Activities Component

src/components/UpcomingEvents/index.jsx, src/components/UpcomingEvents/styles.css
just fix the space between header and paragraph and edit bg-image position to be like the design
=> Fix upcoming events styles bugs

src/components/NewsAndArticles/index.jsx, src/components/NewsAndArticles/styles.css
I Just fix some issues in news and articles section like 
image size
hover effect
links 
unnecessary functions
and edit some components
=> Fix news and articles

src/components/ContactInfo/styles.css
fix color and hover effect to match design
=> fix hover and color style

src/components/UpcomingEvents/index.jsx, src/components/UpcomingEvents/styles.css, src/components/UpcomingEventsCard/index.jsx, src/components/UpcomingEventsCard/style.css
https://tramsi.charity.m3ntorship.com/
=> Upcoming Events section Fixing styles.

.gitignore, package.json, src/components/WorkStyle/index.jsx, src/components/WorkStyle/styles.css, src/components/WorkStyleCard/index.jsx, yarn.lock
- used react-spring to achieve animation effect
- used object mapping to take border color from backend
x - need to look more into how to achieve fade animation with react-spring
=> Fix how we work

src/components/Causes/index.jsx, src/components/Causes/style.css
- Changed button hover style 
- changed background img to be in css
- spacing between heading and description
=> Fix Popular causes styles

src/components/FeaturedBanner/index.jsx, src/components/FeaturedBanner/styles.css
Changed button style and icon position
=> Fix Featured Banner styles

src/css/global.css
Removed body min width and increased container width in smaller screens
=> Resonsive Global

src/components/ContactTop/index.jsx, src/components/ContactTop/style.scss, src/components/Header/index.jsx
these 2 sections will not be displayed in smaller screens
=> Responsive top contact

src/components/MainContact/index.jsx
fixed an issue in contact top section where blue icons would disappear on 768 - 900 px screen sizes
=> fix contact top section

src/components/HeaderCarousel/index.js, src/components/HeaderCarousel/styles.css
1 - i implement carousel responsive in breakepoint max-width:768px
2 - You need to add display:none; to nav to test the component responsive clearly
=> make main carousel responsive

src/components/Activities/index.jsx, src/components/Activities/styles.css
- Activities Cards, displaying them using grid system.
- Adjusted section heading & description width to be responsive in different screen sizes.
=> Responsive activities section

src/components/HeaderCarousel/index.js
- Disabled touching if slides < 1
=> Responsiveness Bugfix: Header Section

src/components/Welcome/styles.css
##Issue:
- Bug at view 768 
##: 
- Change tablet layout to use grid instead of flex.
=> feature-fix/responsive-welcome  Bug:768

src/components/Causes/index.jsx, yarn.lock
I made the loader component to causes section in large and small screens
=> Causes loader

src/components/Causes/index.jsx, src/components/NewsAndArticles/index.jsx
=> News and articles loader

src/components/FeaturedBanner/ContentLoader/index.jsx, src/components/FeaturedBanner/index.jsx
- added content loader for featured banner
=> content-loader-feautred-banner

package.json, src/components/WorkStyle/index.jsx, yarn.lock
=> added content loader for how we work section

src/components/Sponsers/index.jsx
implement react hooks on component
add loader state component
=> Sponsers loader and hooks

src/components/Activities/ActivitiesContentLoading/index.jsx, src/components/Activities/index.jsx
=> Loading content( Activities section)

src/components/WorkStyle/index.jsx
using hooks in component and remove some unnecessary code
=> Hooks work style

src/components/ContactTop/index.jsx
=> useHooks: Contact Top

src/components/Footer/index.jsx
=> Animate: Footer

src/components/HeaderCarousel/index.js
Added animation to main Slider Text
=> Animate: main slider

src/App.js, src/components/Footer/index.jsx, src/stories/8-Footer.stories.js
=> StoryBook: Footer

src/App.js, src/components/Activities/index.jsx, src/stories/7-Activities.stories.js
- Convert Activities component to a story
=> StoryBook: Activities

src/components/Header/index.jsx, src/components/HeaderCarousel/index.js, src/stories/9-HeaderCarousel.stories.js
- Convert Header Carousel to a story
=> StoryBook: HeaderCarousel

src/components/HeaderCarousel/index.js, src/components/MainNavigation/index.jsx, src/stories/MainNavigation.stories.js
- Convert Navigation to a story
=> StoryBook: Navigation

src/components/Logo/index.jsx
- editing logo code to fix an issue where navigation story would try to fetch logo data and couldn't find it and then throw an error
=> Fix/StoryBook:Navigation

src/components/WorkStyle/index.jsx, src/components/WorkStyleCard/index.jsx, src/stories/WorkStyleCard.stories.js
- Converted WorkStyle Card to (Hooks, Storybook)
=> StoryBook: WorkStyleCard

src/components/ArticleBanner/index.js, src/components/ArticleBanner/styles.css
- div that contains links was not aligned correctly
- I used CSS grid to style  elements 
- change the position of the div that contains links.
=> fixed alignment bug

src/components/ContactInfo/index.jsx
I used map index as a unique key
=> add ContactInfo unique key

src/components/MainNavigation/index.jsx
=> used pages CT to dsiplay links that will navigate to website pages

src/App.js, src/components/Header/index.jsx, src/components/HeaderCarousel/index.js, src/components/MainNavigation/index.jsx
_ remove headerCarousel component to be just in the home Page
=> Separate header component

src/App.js, src/components/ArticleBanner/index.js, src/containers/ArticleDetails/index.jsx
what I did 
1 - remove the article page folder from the page folder in the component folder and put it in the container folder and delete the page folder.
2 - fetch the banner data from strapi instead of using static data
3 - edit the banner destruction to simulate the API
4 - and use static two `NavigationLink` components instead of mapping
=> Single Article page container

src/components/MainNavigation/index.jsx
computed  the state of main navigation links from (pages state)
=> computed  main navigation links from redux state (Pages)

src/store/actions/contactInfo.js, src/store/reducers/contact.js
here I create the data sanitization function like Elhaw PR 
but in the actions file __  like Ayoub Comment on the PR __
=> feature/sanitizing Contact data

src/components/Activities/index.jsx, src/store/actions/activities.js, src/store/actions/featuredBanner.js
- Sanitize activities component. 
- Done
=> sanitize activities component

src/store/reducers/activities.js, src/store/reducers/articles.js, src/store/reducers/footer.js, src/store/reducers/headercarousel.js, src/store/reducers/logo.js, src/store/reducers/numbers.js, src/store/reducers/testimonials.js, src/store/reducers/upcomingEvents.js
If the data is not fetched from the server for some reason. The code under this condition is executed 
> `if(data) {//return our UI and consume the data//} // if data is truthy  return our UI`
which cause an error because are trying to consume the `data` which value is data initial state( an empty object `{}` )
If data was not fetched from the server the data value is an empty object `{}` and the condition should evaluates to `falsy` and the code under this condition will not be executed. 
In javascript, an empty object is not considered as  `falsy` so code under this condition get  executed 
> `if({}) { //the code will be excuted }`
Initialize data to a falsy value which is `null`
- If you want to read more about truthy and falsy in Javascript:-
[MDN …
=> set initial value of data to null
